package com.smartcampus.service;

import com.smartcampus.model.Interview;
import com.smartcampus.model.InterviewPanel;
import com.smartcampus.model.InterviewRound;
import com.smartcampus.model.RecruitmentDrive;
import com.smartcampus.repository.InterviewPanelRepository;
import com.smartcampus.repository.InterviewRepository;
import com.smartcampus.repository.InterviewerRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Builds the "when and where" block that goes into every student-facing round email:
 * date, time, room/venue, panel and panel members. Falls back to the drive date and the
 * round's panel when an individual slot hasn't been generated by the scheduler yet, so a
 * student is never emailed a round with no logistics at all.
 */
@Service
@RequiredArgsConstructor
public class ScheduleFormatter {

    private final InterviewRepository interviewRepository;
    private final InterviewPanelRepository panelRepository;
    private final InterviewerRepository interviewerRepository;

    public String scheduleBlock(String studentId, RecruitmentDrive drive, InterviewRound round) {
        if (round == null) {
            return "";
        }

        Interview interview = interviewRepository.findByStudentId(studentId).stream()
                .filter(i -> round.getId().equals(i.getRoundId()))
                .findFirst()
                .orElse(null);

        InterviewPanel panel = Optional.ofNullable(interview)
                .map(Interview::getPanelId)
                .flatMap(panelRepository::findById)
                .orElseGet(() -> panelRepository.findByRoundId(round.getId()).stream().findFirst().orElse(null));

        StringBuilder sb = new StringBuilder();
        sb.append("Schedule for ").append(roundLabel(round)).append(":\n");

        if (interview != null && interview.getDate() != null) {
            sb.append("  Date: ").append(interview.getDate()).append("\n");
            if (interview.getStartTime() != null) {
                sb.append("  Time: ").append(interview.getStartTime());
                if (interview.getEndTime() != null) {
                    sb.append(" - ").append(interview.getEndTime());
                }
                sb.append("\n");
            }
        } else if (drive != null && drive.getDriveDate() != null) {
            sb.append("  Date: ").append(drive.getDriveDate()).append(" (drive date — your exact slot will be confirmed)\n");
        } else {
            sb.append("  Date: to be announced\n");
        }

        String room = interview != null && interview.getVenue() != null && !interview.getVenue().isBlank()
                ? interview.getVenue()
                : panel != null ? panel.getVenue() : null;
        sb.append("  Room / venue: ").append(room == null || room.isBlank() ? "to be announced" : room).append("\n");

        if (panel != null) {
            sb.append("  Panel: ").append(panel.getPanelName()).append("\n");
            List<String> members = interviewerRepository.findAllById(
                            panel.getInterviewerIds() == null ? List.of() : panel.getInterviewerIds()).stream()
                    .map(i -> i.getName())
                    .collect(Collectors.toList());
            if (!members.isEmpty()) {
                sb.append("  Panel members: ").append(String.join(", ", members)).append("\n");
            }
        } else {
            sb.append("  Panel: to be announced\n");
        }

        if (interview != null && interview.getMeetingLink() != null && !interview.getMeetingLink().isBlank()) {
            sb.append("  Meeting link: ").append(interview.getMeetingLink()).append("\n");
        }

        return sb.toString();
    }

    public String roundLabel(InterviewRound round) {
        if (round == null) return "the next round";
        return round.getSequence() == null
                ? round.getRoundName()
                : String.format("Round %d: %s", round.getSequence(), round.getRoundName());
    }
}
